-- seed.sql — intentionally minimal after Phase 12.
--
-- The full static catalog (categories, vendors, products, reviews, regions, product options)
-- now ships as a committed data migration:
--   supabase/migrations/20260711000000_remove_ai_catalog_static_data.sql
--
-- During `db:reset`, Supabase applies all migrations first, then runs this seed file.
-- Catalog rows are already present from the migration — do not re-insert them here or
-- `db:reset` will fail on duplicate-key conflicts.
--
-- Add dev-only test fixtures here if needed (e.g. test user profiles, dummy orders).
-- Keep them idempotent (on conflict do nothing) so repeated resets are safe.
